# Generated by Django 4.2.2 on 2023-07-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('CustomerName', models.CharField(max_length=200, null=True)),
                ('Product', models.CharField(max_length=200, null=True)),
                ('Quantity', models.FloatField(max_length=50, null=True)),
                ('TotalAmount', models.FloatField(max_length=50, null=True)),
            ],
        ),
    ]
